### Numpy : Numerical Python
### 수치계산용 파이썬 라이브러리

In [4]:
import numpy as np

# 넘파이 배열(리스트) 생성하기
# np.array() 함수사용
a = np.arange(10)
a

a2 = np.arange(3,9,1)
a2  # 3,4,5,6,7,9

a3 = np.arange(3,9,2)
a3  # 3, 5, 7


array([3, 5, 7])

In [5]:
# 넘파이 배열(리스트) 생성하기
# np.array() 함수사용
b = [1, 2, 3, 4]
arr = np.array(b)
arr

array([[1, 2, 3, 4]])

In [6]:
import numpy as np

c = ['봄','여름', '가을','겨울']
arr2 = np.array(c)
arr2
#print(arr2)


array(['봄', '여름', '가을', '겨울'], dtype='<U2')

In [7]:
import numpy as np

c = [1.0,2,3,4]
arr2 = np.array(c)
arr2
print(arr2)
print(arr2.dtype)

[1. 2. 3. 4.]
float64


In [8]:
import numpy as np

c = ['봄','여름', '가을', '겨울']
arr2 = np.array(c)
arr2
print(arr2)
print(arr2.dtype)


['봄' '여름' '가을' '겨울']
<U2


In [11]:
import numpy as np

순위 = 1 + np.arange(10) # 1 + (0~9)

팀 = np.array(['SSG','LG','키움','KT','기아','NC','삼성','롯데','두산','한화'])
승 = np.array([88,87,80,80,70,67,66,64,60,46])
패 = np.array([52,55,62,62,73,74,76,76,82,96])
무 = np.array([4, 2, 2, 2, 1, 3, 2, 4, 2, 2])
승률 = np.array([0.629, 0.613, 0.583, 0.583, 0.490,0.475, 0.485, 0.457, 0.423, 0.324])
# print(팀)
# print(승)
# print(len(팀))

with open("datas/2022kbo.txt", 'w') as f:
    f.write("========= 2022 한국 프로 야구 성적표 ===========\n")
    head = "순위\t팀\t승\t패\t무\t승률"
    f.write(head)
    f.write('\n')
    for i in range(len(팀)): # 10번 반복
        txt = f'{순위[i]}\t{팀[i]}\t{승[i]}\t{패[i]}\t{무[i]}\t{승률[i]}\n'
        f.write(txt)

In [15]:
with open("datas/2022kbo.txt", 'r') as f:
    data = f.read()
    print(data)

========= 2022 한국 프로 야구 성적표 ===========
순위	팀	승	패	무	승률
1	SSG	88	52	4	0.629
2	LG	87	55	2	0.613
3	키움	80	62	2	0.583
4	KT	80	62	2	0.583
5	기아	70	73	1	0.49
6	NC	67	74	3	0.475
7	삼성	66	76	2	0.485
8	롯데	64	76	4	0.457
9	두산	60	82	2	0.423
10	한화	46	96	2	0.324



### 넘파이의 N차원배열
#### 1차원 배열은 벡터(vector)라 함
### 2차원 배열은 행렬(matrix) - 수,또는 문자를 괄호한에 직사각형 형태로 배열
### 3차원 배열은 텐서(tensor)라 함

In [44]:
A = np.array([[1,2], [3,4]]) 
B = np.array([[3,0], [0,6]])
# print(A)
# print(A.shape) #2행 2열

# print(B)
# print(B.shape) #2행 2열

# 인덱싱
print(A[0])
print(A[0][1])
print(A[1][1])

#전체조히
for row in B:
    print(row)

# 연산
# print(A+B)
# print(A-B)
# print(A*B)
# print(A/B)

[1 2]
2
4
[3 0]
[0 6]
